global:
  scrape_interval: 5s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "fastapi"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
